name: cafenow_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  kakaomap_webview: ^0.6.2
  webview_flutter: ^3.0.1
  url_launcher: ^6.1.0

  # location
  geolocator: ^9.0.1

  # logging
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/icons/
